title: Learning Everyday 
author: AC
email: .com
description: > # this means to ignore newlines until "baseurl:"
  Learning about Data


# social links
github_username:  Corky2407

show_excerpts: true # set to false to remove excerpts on the homepage

theme: mini
